### ISSUE TITLE
不能用在被TextInputLayout包裹的EditText

### ISSUE THREAD

**Issue by xjl12** [covetcode/EditTextFirework-Demo#1]
我的项目使用了TextInputLayout包裹住EditText，这样用户在输入时，hint属性规定的文字就会浮于EditText上方，但是我使用EditTextFirework时，烟花没有正确显示在EditText光标闪烁处，而是显示在布局的顶部。
以下是我使用的布局代码:
<android.support.design.widget.TextInputLayout
 		android:layout_height="@dimen/height_0"
 		android:layout_width="match_parent"
 		android:id="@+id/main_TextInputLayout"
 		app:counterEnabled="true">
     <EditText
        android:layout_height="wrap_content"
        android:layout_width="match_parent"
        android:hint="@string/main_edit_hint"
        android:gravity="center"
        android:id="@+id/main_m_input"
        android:layout_centerInParent="true"/>
 
</android.support.design.widget.TextInputLayout>
<com.wayww.edittextfirework.FireworkView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:id="@+id/fire_work"/>

我希望它能够正常工作在这种情形中。

**Comment by xjl12** [comment]
布局代码打错了，抱歉！
<android.support.design.widget.TextInputLayout
    android:layout_height="@dimen/height_0"
    android:layout_width="match_parent"
    android:id="@+id/main_TextInputLayout"
    app:counterEnabled="true">
    <EditText
        android:layout_height="wrap_content"
        android:layout_width="match_parent"
        android:hint="@string/main_edit_hint"
        android:gravity="center"
        android:id="@+id/main_m_input"/>

 </android.support.design.widget.TextInputLayout>

<com.wayww.edittextfirework.FireworkView
android:layout_width="match_parent"
android:layout_height="match_parent"
android:id="@+id/fire_work"/>

**Comment by xjl12** [comment]
Github编辑文本好奇怪，在TextInputLayout中是有一个EditText的，怎么没显示出来。

换句话说，FireworkView和EditText不在同一个Layout，就出现了这样的错误。

**Comment by covetcode** [comment]
我已经修复了这个bug，并提交了代码。

具体为在FireworkView 里的

getCursorCoordinate （）方法的最后加入：

        float x = mEditText.getX() + xOffset;
        float y = mEditText.getY() + yOffset;

        //当EditText的父view与FireworkView的坐标（左上角的坐标值）不一致时进行修正
        int[] positionE = new int[2];
        if (mEditText.getParent() != null) {
            ((ViewGroup)mEditText.getParent()).getLocationInWindow(positionE);
        }
        int[] positionF = new int[2];
        this.getLocationInWindow(positionF);
        x = x+positionE[0]-positionF[0];
        y = y+positionE[1]-positionF[1];

        return new float[]{x , y};

**Comment by xjl12** [comment]
嗯，我试了下，这个bug的确修复了，很棒！
